<a href="https://colab.research.google.com/github/Connoroverbay/wrangling/blob/main/WranglingAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1:


1.   The paper is about the concept of tidy data and how defining "tidy" will help to create a more universal standard for data entry and editing. This will also help with future data analysis.
2.   The tidy data standard would hopefully make data analysis more effective and less time consuming by allowing for software packages to begin data analysis immediately, instead of having to go through the extensive data tidying process.
3.   The first sentence highlights the usefulness of tiny data by emphasizing how it allows for a general data analysis code to work for any tidy data set, whereas messy data never would have a general soulution and each problem must be solved on a case by case basis. The second sentence is refering to the problem with some data sets not being labeled in easily understandable syntax, therefore causing problems when data analysis takes places.
4.   Values are the specific data points collected for an individual variable and observation combination, a variable is an observable quality that can be recorded from an observation, and an observation is a set of values that correspond to one particular unit in a study or panel.
5.   Tidy data is when each variable is restricted to one column, each observation to one row, and the observational units(if applicable) are organized by their specific units into subtables.
6.   The five most common problems with messy data are:

  • Column headers are values, not variable names.

  • Multiple variables are stored in one column.

  • Variables are stored in both rows and columns.

  • Multiple types of observational units are stored in the same table.

  • A single observational unit is stored in multiple tables.

      This table is messy because the variable column headings are not actual variables but rather values. The rows of the table are also variables and not actual observations. Melting refers to the process of turning columns headers that are variables into rows in order to better group the observations for data analysis.

7.   Table 11 is messy because 1) it contains an excessive amount of missing data and 2) the variables in the column headings should be included as separate rows to help with data analysis.
8.   The chicken and egg problem refers to the idea that if tidy data as defined here is only as good as the programs used to analyze it, then there will be a lacking use of other data repositories that also contain useful information. To combat this, the author hopes that people will continue to create new frameworks and programs to analyze datasets in similar, efficent ways.

Question 2:

In [2]:
import pandas as pd
import numpy as np
import os
os.getcwd()

'/content'

In [4]:
df = pd.read_csv('/content/airbnb_hw.csv', low_memory=False)
df.head(10)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
5,1039,7/25/2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0
6,1783,8/12/2008,Amazing Also,Manhattan,Apartment,100.0,Entire home/apt,10004.0,1.0,1,9,250,100.0
7,2078,8/15/2008,"Colorful, quiet, & near the subway!",Brooklyn,Apartment,90.0,Private room,11201.0,1.0,1,80,90,94.0
8,2339,8/20/2008,East Village Cocoon: 2 Bedroom Flat,Manhattan,Apartment,90.0,Entire home/apt,10009.0,2.0,1,95,270,90.0
9,2339,8/20/2008,Lovely 2 Bedroom East Village Nest,Manhattan,Apartment,95.0,Entire home/apt,10009.0,2.0,1,23,290,96.0

In [5]:
df['Price'].unique()
prices = df['Price']
prices = prices.str.replace(',','')
prices = pd.to_numeric(prices)
prices.unique()
print(np.mean(prices))

163.58973685937397

The changes made in this section were to remove all of the commas inside of the prices category for numbers over 1000 so that the variable could by typecasted into a numeric variable type and used for computational purposes in data analysis. The mean command at the end was to check and make sure that the typecast was successful. The code would return an error if the variable was still a string. This is also more effective than other methods because it does not require removing any data values.

In [6]:
df = pd.read_csv('/content/sharks.csv', low_memory=False)
df.head(10)

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,0,2020.02.05,05-Feb-2020,2020.0,Unprovoked,USA,Maui,NaN,Stand-Up Paddle boarding,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020.01.30.R,Reported 30-Jan-2020,2020.0,Provoked,BAHAMAS,Exumas,NaN,Floating,Ana Bruna Avila,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020.01.17,17-Jan-2020,2020.0,Unprovoked,AUSTRALIA,New South Wales,Windang Beach,Surfing,Will Schroeter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2020.01.16,16-Jan-2020,2020.0,Unprovoked,NEW ZEALAND,Southland,Oreti Beach,Surfing,Jordan King,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020.01.13,13-Jan-2020,2020.0,Unprovoked,USA,North Carolina,"Rodanthe, Dare County",Surfing,Samuel Horne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,2020.01.12,12-Jan-2020,2020.0,Unprovoked,THAILAND,Phang Nga Province,Nang Thong Beach,Swimming,Hans-Peter Malten,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,2020.01.07,07-Jan-2020,2020.0,Unprovoked,AUSTRALIA,Queensland,North West Island,Swimming,Miah Holmes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,2020.01.05,05-Jan-2020,2020.0,Unprovoked,AUSTRALIA,Western Australia,Cull Island / Esperance,Scuba diving,Gary Johnson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,2020.01.03,03-Jan-2020,2020.0,Unprovoked,NEW CALEDONIA,NaN,Calana,NaN,Peter ___,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,2020.01.02,02-Jan-2020,2020.0,Questionable,AUSTRALIA,Western Australia,Esperance,Swimming after being swept off rocks,Eric Birighitti,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df['Type'].value_counts()
types = df['Type']
types = types.replace(['Questionable','Unconfirmed','Unverified','Under investigation','Invalid'],'Unknown')
types = types.replace(['Sea Disaster','Boating','Boat','Watercraft','Boatomg'],'Water Incident')
df['Type']=types
df['Type'].value_counts()

Unprovoked        4716
Provoked           593
Water Incident     583
Unknown            565
Name: Type, dtype: int64

The data seemed to have too many similar categorical options for the Type of incident so I combined some of the similar ones into larger categories that will be more helpful for analysis. Also one of the subcategories was a clear typo so I included it in the larger category if it was spelled right.

In [8]:
url = 'http://www.vcsc.virginia.gov/pretrialdataproject/October%202017%20Cohort_Virginia%20Pretrial%20Data%20Project_Deidentified%20FINAL%20Update_10272021.csv'
df = pd.read_csv(url,low_memory=False)
df.head(10)

,InternalStudyID,REQ_REC#,Defendant_Sex,Defendant_Race,Defendant_BirthYear,Defendant_Age,Defendant_AgeGroup,Defendant_AgeatCurrentArrest,Defendant_AttorneyTypeAtCaseClosure,Defendant_IndigencyStatus,...,NewFelonySexualAssaultArrest_OffDate,NewFelonySexualAssaultArrest_ArrestDate,NewFelonySexualAssaultArrest_DaysBetweenContactEventandOffDate,NewFelonySexualAssaultArrest_DaysBetweenOffDateandArrestDate,NewFelonySexualAssaultArrest_DaysBetweenReleaseDateandOffDate,NewFelonySexualAssaultArrest_Disposition,Intertnalindicator_ReasonforExcludingFromFollowUpAnalysis,CriminalHistoryRecordsReturnedorCMSRecordsFoundforIndividual,DispRecordFoundforChargesinOct2017Contact_Atleast1dispfound,CrimeCommission2021ReportClassificationofDefendants
0,ADI00001,1,M,W,1986,31,3,31,99,99,...,,,,999,999,,4,1,0,Defendant could not be classified or tracked d...
1,ADI00007,3,M,B,1956,60,6,60,9,9,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
2,ADI00008,4,M,W,1990,27,3,27,9,9,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
3,CDI00036,6,M,B,1989,27,3,27,0,0,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
4,CDI00038,7,F,W,1988,28,3,28,0,0,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...
5,CDI00039,8,M,B,1978,39,4,39,0,0,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
6,CDI00041,9,F,B,1981,35,3,35,1,1,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...
7,CDI00043,10,M,B,1999,18,2,18,0,0,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...
8,CDI00044,11,M,B,1990,27,3,27,1,1,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
9,CDI00046,12,M,W,1996,21,2,21,1,1,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...

In [ ]:
df.columns.to_list()

In [9]:
release = df['WhetherDefendantWasReleasedPretrial']
release = release.replace(0,"No")
release = release.replace(1,"Yes")
release = release.replace('', np.nan)
df['WhetherDefendantWasReleasedPretrial'].rename("Released Pretrial")
df['Released Pretrial'] = release
df.head()
df['Released Pretrial'].value_counts()

Yes    19154
No      3801
9         31
Name: Released Pretrial, dtype: int64

In [34]:
df['ImposedSentenceAllChargeInContactEvent']
df['SentenceTypeAllChargesAtConvictionInContactEvent']

time = df['ImposedSentenceAllChargeInContactEvent']
type = df['SentenceTypeAllChargesAtConvictionInContactEvent']
time = pd.to_numeric(time,errors = 'coerce')
time = time.mask( type == 4, 0)
time = time.mask( type == 9, np.nan)

type = type.replace(0,"No Incarceration")
type = type.replace(1,"Jail Under 12 Months")
type = type.replace(2, 'Prison')
type = type.replace(4,"Dismissed")
type = type.replace(9,"Unknown")

type.value_counts()

Dismissed               8779
No Incarceration        8720
Jail Under 12 Months    4299
Prison                   914
Unknown                  274
Name: SentenceTypeAllChargesAtConvictionInContactEvent, dtype: int64

To tidy this data, the first thing I did was look into the codebook to see what exactly the data was refering to in order to best clean the data effectively. One variable refers to time length of sentence whereas the other refers to the type of sentencing recieved. To clean this I changed the time variable to a numeric type so that algebraic calculations could be computed. I then changed the numeric coding of the type of sentencing to easily understood strings that make analysis of the count of specific values more clear. Also most of the data entries for time length of sentence was registered as NA when in reality it just refered to any case that was dismissed, therefore not having any data for sentence length. To fix this I replaced the NA values with 0.